name: adaro
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ^3.10.1

dependencies:
  animations: ^2.2.0
  auto_route: ^10.2.2
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_foreground_task: ^8.16.0
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_svg: ^2.3.0
  freezed_annotation: ^3.0.0
  geolocator: ^13.0.4
  get_it: ^8.0.3
  injectable: ^2.5.0
  intl: ^0.20.2
  latlong2: ^0.9.1
  lucide_icons_flutter: ^3.1.11
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  shared_preferences: ^2.3.5
  slang: ^3.31.0
  slang_flutter: ^3.31.0
  toastification: ^3.2.0

dev_dependencies:
  auto_route_generator: ^10.2.6
  build_runner: ^2.10.4
  drift_dev: ^2.26.0
  freezed: ^3.0.0
  injectable_generator: ^2.7.0
  prefer_shorthands: ^0.4.7

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
